version: '3.8'

# Alternative compose file using SQLite for quick demos
# Usage: docker-compose -f docker-compose.sqlite.yml up

services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - VITE_BACKEND=node
      - VITE_API_URL=http://localhost:3000
      - VITE_REALTIME_BACKEND=socketio
    depends_on:
      - backend-node
    networks:
      - app-network

  # Node.js Backend with SQLite
  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_DIALECT=sqlite
      - DB_STORAGE=/app/data/database.sqlite
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - CORS_ORIGIN=http://localhost:3001
    volumes:
      - node-uploads:/app/uploads
      - sqlite-data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite-data:
  node-uploads:
